name: Deploy

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./demo
jobs:
  deploy:
    name: build image and run it
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Write File
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: ./src/main/resources/properties/env.properties
          contents: database.password=${{ secrets.DATABASE_PASSWORD }}
          write-mode: overwrite

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.3.0
        with:
          arguments: build
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
      
      # - name: Build with Gradle
      #   uses: gradle/actions@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./build/libs/
          file: ./build/libs/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/duckling-back:latest

      - name: Pull and restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script:
            docker container stop duckling-back;
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/duckling-back;
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/duckling-back:latest;
            docker run -d --rm --name duckling-back -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/duckling-back:latest;
