name: Deploy

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: .
jobs:
  deploy:
    name: build image and run it
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v4.0.2
      #   with:
      #     node-version: 20

      # - name: Cache node modules
      #   uses: actions/cache@v4.0.2
      #   id: cache
      #   with:
      #     path: node_modules
      #     key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      # - name: Install Dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm install

      # - name: Build
      #   run: npm run build

      - name: Write File
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: ./demo/src/main/resources/properties/env.properties
          contents: database.password=${{ secrets.DATABASE_PASSWORD }}
          write-mode: overwrite

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./demo/build/libs
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/duckling-back:latest

      - name: Pull and restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script:
            docker container stop duckling-back;
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/duckling-back;
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/duckling-back:latest;
            docker run -d --rm --name duckling-back -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/duckling-back:latest;
